# Generated by Django 3.2.16 on 2023-01-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slug',
            new_name='writer',
        ),
    ]
