# Generated by Django 3.2.16 on 2023-01-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_content_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
